version: '3.1'

services:
  tkpwp_app:
    image: prakasa1904/wp-environment:latest
    container_name: tkpwp_app
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
    ports:
      - 8080:80