version: '3.1'

services:
  buckler_app:
    image: prakasa1904/wp-environment:latest
    container_name: buckler_app
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
    ports:
      - 8080:80
    env_file: .env